# Generated by Django 3.2.16 on 2022-11-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0168_suggestedbookgenre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minimumvotessetting',
            old_name='minimum_votes',
            new_name='minimum_book_votes',
        ),
        migrations.AddField(
            model_name='minimumvotessetting',
            name='minimum_genre_votes',
            field=models.IntegerField(default=10),
        ),
    ]
