# Generated by Django 3.2.16 on 2022-11-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0173_merge_20221115_2303'),
        ('bookwyrm', '0173_merge_20221117_1523'),
    ]

    operations = [
    ]
