# Generated by Django 3.2.16 on 2022-11-28 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0174_merge_20221117_1658'),
        ('bookwyrm', '0176_merge_20221118_1722'),
    ]

    operations = [
    ]
