# Generated by Django 3.2.16 on 2022-12-07 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0167_auto_20221125_1900'),
        ('bookwyrm', '0176_merge_20221118_1722'),
    ]

    operations = [
    ]
