# Generated by Django 3.2.16 on 2022-12-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0170_merge_0168_auto_20221205_2331_0169_auto_20221206_0902"),
        ("bookwyrm", "0177_merge_20221207_0026"),
    ]

    operations = []
