# Generated by Django 3.2.16 on 2022-12-11 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0177_merge_20221128_0057'),
        ('bookwyrm', '0178_merge_20221211_2219'),
    ]

    operations = [
    ]
