# Generated by Django 3.2.16 on 2022-12-24 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0172_alter_user_preferred_language"),
        ("bookwyrm", "0178_merge_20221211_2219"),
    ]

    operations = []
