# Generated by Django 3.2.16 on 2023-01-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0173_default_user_auth_group_setting'),
        ('bookwyrm', '0179_merge_20221224_2031'),
    ]

    operations = [
    ]
