# Generated by Django 3.2.18 on 2023-03-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0174_auto_20230130_1240"),
        ("bookwyrm", "0180_merge_20230130_1821"),
    ]

    operations = []
