# Generated by Django 3.2.18 on 2023-05-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0178_auto_20230328_2132'),
        ('bookwyrm', '0181_merge_20230301_1422'),
    ]

    operations = [
    ]
